### ISSUE TITLE
Variable confusion

### ISSUE THREAD

**Issue by lucasrodes** [COVID19-Malta/COVID19-Data#12]
Hi @hugoamuscat @stefanbuttigieg @agiuh001,
We have realized that since 28/09/2021, the value of `Fully vaccinated (2 of 2 or 1 of 1)` exceeds the one of `Received one dose (1 of 2 or 1 of 1)`.

My understanding so far was that `Received one dose (1 of 2 or 1 of 1)` measured the number of people with **at least** one dose. If so, this should always be greater than the number of fully vaccinated people.

Could you clarify on this? Thanks!

**Comment by agiuh001** [comment]
Dear Lucas,

We noticed this as soon as it started happening, because we calculate other statistics based on these figures, which are provided by the Vaccination Team.  The explanation we received was that not all the first doses of completed two-dose courses have been recorded yet, owing to procedural issues.  When we explained that this will result in anomalies if calculations are carried out on the figures, they appreciated the issue and pledged to record the missing data as possible so that the data in column 'Received one dose (1 of 2 or 1 of 1)' is complete.  If this process takes long, we will consider unpublishing the column if we see that this is causing concern or misunderstanding.  Hope this clarifies.

Best regards,
Hugo Agius Muscat
